<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SystemOption;

class SystemOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $options = [
            // Attachment Types
            [
                'category' => 'attachment_type',
                'value' => 'voucher',
                'label' => 'Voucher',
                'color' => '#3B82F6',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'Disbursement voucher documents',
            ],
            [
                'category' => 'attachment_type',
                'value' => 'cheque',
                'label' => 'Cheque',
                'color' => '#10B981',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Cheque copies or images',
            ],
            [
                'category' => 'attachment_type',
                'value' => 'receipt',
                'label' => 'Receipt',
                'color' => '#8B5CF6',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Payment receipts and acknowledgments',
            ],

            // Grant Provisions
            [
                'category' => 'grant_provision',
                'value' => 'Matriculation',
                'label' => 'Matriculation',
                'color' => '#EF4444',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'Enrollment and registration fees',
            ],
            [
                'category' => 'grant_provision',
                'value' => 'RLE',
                'label' => 'RLE',
                'color' => '#F59E0B',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Related Learning Experience',
            ],
            [
                'category' => 'grant_provision',
                'value' => 'Tuition',
                'label' => 'Tuition',
                'color' => '#06B6D4',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Tuition and academic fees',
            ],
            [
                'category' => 'grant_provision',
                'value' => 'RLE and Tuition',
                'label' => 'RLE and Tuition',
                'color' => '#8B5CF6',
                'sort_order' => 4,
                'is_active' => true,
                'description' => 'Combined RLE and tuition support',
            ],

            // OBR Status
            [
                'category' => 'obr_status',
                'value' => 'LOA',
                'label' => 'LOA',
                'color' => '#6B7280',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'Leave of Absence',
            ],
            [
                'category' => 'obr_status',
                'value' => 'IRREGULAR',
                'label' => 'Irregular',
                'color' => '#F59E0B',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Irregular enrollment status',
            ],
            [
                'category' => 'obr_status',
                'value' => 'TRANSFERRED',
                'label' => 'Transferred',
                'color' => '#3B82F6',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Transferred to another institution',
            ],
            [
                'category' => 'obr_status',
                'value' => 'CLAIMED',
                'label' => 'Claimed',
                'color' => '#10B981',
                'sort_order' => 4,
                'is_active' => true,
                'description' => 'Funds have been claimed',
            ],
            [
                'category' => 'obr_status',
                'value' => 'PAID',
                'label' => 'Paid',
                'color' => '#059669',
                'sort_order' => 5,
                'is_active' => true,
                'description' => 'Payment completed',
            ],
            [
                'category' => 'obr_status',
                'value' => 'ON PROCESS',
                'label' => 'On Process',
                'color' => '#6366F1',
                'sort_order' => 6,
                'is_active' => true,
                'description' => 'Currently being processed',
            ],
            [
                'category' => 'obr_status',
                'value' => 'DENIED',
                'label' => 'Denied',
                'color' => '#EF4444',
                'sort_order' => 7,
                'is_active' => true,
                'description' => 'Request has been denied',
            ],

            // Disbursement Types
            [
                'category' => 'disbursement_type',
                'value' => 'regular',
                'label' => 'Regular',
                'color' => '#10B981',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'Regular scholarship disbursement',
            ],
            [
                'category' => 'disbursement_type',
                'value' => 'reimbursement',
                'label' => 'Reimbursement',
                'color' => '#F59E0B',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Reimbursement of expenses',
            ],
            [
                'category' => 'disbursement_type',
                'value' => 'financial_assistance',
                'label' => 'Financial Assistance',
                'color' => '#8B5CF6',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Additional financial support',
            ],

            // Priority Levels
            [
                'category' => 'priority_level',
                'value' => 'low',
                'label' => 'Low',
                'color' => '#6B7280',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'Low priority',
            ],
            [
                'category' => 'priority_level',
                'value' => 'normal',
                'label' => 'Normal',
                'color' => '#3B82F6',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Normal priority (default)',
            ],
            [
                'category' => 'priority_level',
                'value' => 'high',
                'label' => 'High',
                'color' => '#F59E0B',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'High priority',
            ],
            [
                'category' => 'priority_level',
                'value' => 'urgent',
                'label' => 'Urgent',
                'color' => '#EF4444',
                'sort_order' => 4,
                'is_active' => true,
                'description' => 'Urgent - requires immediate attention',
            ],

            // Terms (matching existing database values)
            [
                'category' => 'term',
                'value' => '1ST SEMESTER',
                'label' => '1st Semester',
                'color' => '#3B82F6',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'First semester of the academic year',
            ],
            [
                'category' => 'term',
                'value' => '2ND SEMESTER',
                'label' => '2nd Semester',
                'color' => '#10B981',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Second semester of the academic year',
            ],
            [
                'category' => 'term',
                'value' => '3RD SEMESTER',
                'label' => '3rd Semester',
                'color' => '#10B981',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Third semester of the academic year',
            ],
            [
                'category' => 'term',
                'value' => '1ST TRIMESTER',
                'label' => '1st Trimester',
                'color' => '#8B5CF6',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'First trimester (for trimester-based programs)',
            ],
            [
                'category' => 'term',
                'value' => 'SUMMER',
                'label' => 'Summer',
                'color' => '#F59E0B',
                'sort_order' => 4,
                'is_active' => true,
                'description' => 'Summer term',
            ],
            [
                'category' => 'term',
                'value' => 'REVIEW',
                'label' => 'Review',
                'color' => '#EC4899',
                'sort_order' => 5,
                'is_active' => true,
                'description' => 'Review period',
            ],
            [
                'category' => 'term',
                'value' => 'N/A',
                'label' => 'N/A',
                'color' => '#6B7280',
                'sort_order' => 6,
                'is_active' => true,
                'description' => 'Not applicable',
            ],

            // Year Levels (matching existing database values)
            [
                'category' => 'year_level',
                'value' => '1ST',
                'label' => '1st Year',
                'color' => '#3B82F6',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'First year student',
            ],
            [
                'category' => 'year_level',
                'value' => '2ND',
                'label' => '2nd Year',
                'color' => '#10B981',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Second year student',
            ],
            [
                'category' => 'year_level',
                'value' => '3RD',
                'label' => '3rd Year',
                'color' => '#F59E0B',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Third year student',
            ],
            [
                'category' => 'year_level',
                'value' => '4TH',
                'label' => '4th Year',
                'color' => '#EF4444',
                'sort_order' => 4,
                'is_active' => true,
                'description' => 'Fourth year student',
            ],
            [
                'category' => 'year_level',
                'value' => '5TH',
                'label' => '5th Year',
                'color' => '#8B5CF6',
                'sort_order' => 5,
                'is_active' => true,
                'description' => 'Fifth year student',
            ],
            [
                'category' => 'year_level',
                'value' => 'GRADUATE',
                'label' => 'Graduate',
                'color' => '#06B6D4',
                'sort_order' => 6,
                'is_active' => true,
                'description' => 'Graduate level student',
            ],
            [
                'category' => 'year_level',
                'value' => 'REVIEW',
                'label' => 'Review',
                'color' => '#EC4899',
                'sort_order' => 7,
                'is_active' => true,
                'description' => 'Review/preparatory level',
            ],

            // Academic Years (matching existing database values)
            [
                'category' => 'academic_year',
                'value' => '2019-2020',
                'label' => '2019-2020',
                'color' => '#9CA3AF',
                'sort_order' => 1,
                'is_active' => false,
                'description' => 'Academic year 2019-2020',
            ],
            [
                'category' => 'academic_year',
                'value' => '2020-2021',
                'label' => '2020-2021',
                'color' => '#9CA3AF',
                'sort_order' => 2,
                'is_active' => false,
                'description' => 'Academic year 2020-2021',
            ],
            [
                'category' => 'academic_year',
                'value' => '2021-2022',
                'label' => '2021-2022',
                'color' => '#9CA3AF',
                'sort_order' => 3,
                'is_active' => false,
                'description' => 'Academic year 2021-2022',
            ],
            [
                'category' => 'academic_year',
                'value' => '2022-2023',
                'label' => '2022-2023',
                'color' => '#9CA3AF',
                'sort_order' => 4,
                'is_active' => false,
                'description' => 'Academic year 2022-2023',
            ],
            [
                'category' => 'academic_year',
                'value' => '2023-2024',
                'label' => '2023-2024',
                'color' => '#6B7280',
                'sort_order' => 5,
                'is_active' => false,
                'description' => 'Academic year 2023-2024',
            ],
            [
                'category' => 'academic_year',
                'value' => '2024-2025',
                'label' => '2024-2025',
                'color' => '#3B82F6',
                'sort_order' => 6,
                'is_active' => true,
                'description' => 'Academic year 2024-2025',
            ],
            [
                'category' => 'academic_year',
                'value' => '2025-2026',
                'label' => '2025-2026',
                'color' => '#10B981',
                'sort_order' => 7,
                'is_active' => true,
                'description' => 'Academic year 2025-2026',
            ],

            // Form Categories
            [
                'category' => 'form_category',
                'value' => 'Forms',
                'label' => 'Forms',
                'color' => '#3B82F6',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'Scholarship and application forms',
            ],
            [
                'category' => 'form_category',
                'value' => 'Requirements Checklist',
                'label' => 'Requirements Checklist',
                'color' => '#10B981',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Document requirements checklist',
            ],
            [
                'category' => 'form_category',
                'value' => 'Templates',
                'label' => 'Templates',
                'color' => '#8B5CF6',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Document templates',
            ],
            [
                'category' => 'form_category',
                'value' => 'Guidelines',
                'label' => 'Guidelines',
                'color' => '#F59E0B',
                'sort_order' => 4,
                'is_active' => true,
                'description' => 'Program guidelines and policies',
            ],
            [
                'category' => 'form_category',
                'value' => 'Reports',
                'label' => 'Reports',
                'color' => '#EF4444',
                'sort_order' => 5,
                'is_active' => true,
                'description' => 'Report templates and forms',
            ],
            [
                'category' => 'form_category',
                'value' => 'Others',
                'label' => 'Others',
                'color' => '#6B7280',
                'sort_order' => 6,
                'is_active' => true,
                'description' => 'Miscellaneous files and documents',
            ],

            // Religion
            [
                'category' => 'religion',
                'value' => 'Roman Catholic',
                'label' => 'Roman Catholic',
                'color' => '#3B82F6',
                'sort_order' => 1,
                'is_active' => true,
                'description' => 'Roman Catholic Christian',
            ],
            [
                'category' => 'religion',
                'value' => 'Islam',
                'label' => 'Islam',
                'color' => '#10B981',
                'sort_order' => 2,
                'is_active' => true,
                'description' => 'Islam/Muslim',
            ],
            [
                'category' => 'religion',
                'value' => 'Iglesia ni Cristo',
                'label' => 'Iglesia ni Cristo',
                'color' => '#8B5CF6',
                'sort_order' => 3,
                'is_active' => true,
                'description' => 'Iglesia ni Cristo',
            ],
            [
                'category' => 'religion',
                'value' => 'Protestant',
                'label' => 'Protestant',
                'color' => '#F59E0B',
                'sort_order' => 4,
                'is_active' => true,
                'description' => 'Protestant Christian',
            ],
            [
                'category' => 'religion',
                'value' => 'Born Again Christian',
                'label' => 'Born Again Christian',
                'color' => '#EF4444',
                'sort_order' => 5,
                'is_active' => true,
                'description' => 'Born Again Christian',
            ],
            [
                'category' => 'religion',
                'value' => 'Seventh-day Adventist',
                'label' => 'Seventh-day Adventist',
                'color' => '#06B6D4',
                'sort_order' => 6,
                'is_active' => true,
                'description' => 'Seventh-day Adventist',
            ],
            [
                'category' => 'religion',
                'value' => 'Jehovah\'s Witnesses',
                'label' => 'Jehovah\'s Witnesses',
                'color' => '#EC4899',
                'sort_order' => 7,
                'is_active' => true,
                'description' => 'Jehovah\'s Witnesses',
            ],
            [
                'category' => 'religion',
                'value' => 'Buddhism',
                'label' => 'Buddhism',
                'color' => '#F97316',
                'sort_order' => 8,
                'is_active' => true,
                'description' => 'Buddhism',
            ],
            [
                'category' => 'religion',
                'value' => 'Hinduism',
                'label' => 'Hinduism',
                'color' => '#84CC16',
                'sort_order' => 9,
                'is_active' => true,
                'description' => 'Hinduism',
            ],
            [
                'category' => 'religion',
                'value' => 'Life Church',
                'label' => 'Life Church',
                'color' => '#A855F7',
                'sort_order' => 10,
                'is_active' => true,
                'description' => 'Life Church',
            ],
            [
                'category' => 'religion',
                'value' => 'Pentecostal',
                'label' => 'Pentecostal',
                'color' => '#14B8A6',
                'sort_order' => 11,
                'is_active' => true,
                'description' => 'Pentecostal Christian',
            ],
            [
                'category' => 'religion',
                'value' => 'Evangelical',
                'label' => 'Evangelical',
                'color' => '#F59E0B',
                'sort_order' => 12,
                'is_active' => true,
                'description' => 'Evangelical Christian',
            ],
            [
                'category' => 'religion',
                'value' => 'Baptist',
                'label' => 'Baptist',
                'color' => '#EF4444',
                'sort_order' => 13,
                'is_active' => true,
                'description' => 'Baptist Christian',
            ],
            [
                'category' => 'religion',
                'value' => 'Methodist',
                'label' => 'Methodist',
                'color' => '#06B6D4',
                'sort_order' => 14,
                'is_active' => true,
                'description' => 'Methodist Christian',
            ],
            [
                'category' => 'religion',
                'value' => 'Foursquare Gospel Church',
                'label' => 'Foursquare Gospel Church',
                'color' => '#8B5CF6',
                'sort_order' => 15,
                'is_active' => true,
                'description' => 'Foursquare Gospel Church',
            ],
            [
                'category' => 'religion',
                'value' => 'The Church of Jesus Christ of Latter-day Saints (Mormon)',
                'label' => 'The Church of Jesus Christ of Latter-day Saints (Mormon)',
                'color' => '#10B981',
                'sort_order' => 16,
                'is_active' => true,
                'description' => 'The Church of Jesus Christ of Latter-day Saints (Mormon)',
            ],
            [
                'category' => 'religion',
                'value' => 'Bible Baptist Church',
                'label' => 'Bible Baptist Church',
                'color' => '#F97316',
                'sort_order' => 17,
                'is_active' => true,
                'description' => 'Bible Baptist Church',
            ],
            [
                'category' => 'religion',
                'value' => 'Philippine Independent Church',
                'label' => 'Philippine Independent Church (Aglipayan)',
                'color' => '#EC4899',
                'sort_order' => 18,
                'is_active' => true,
                'description' => 'Philippine Independent Church (Aglipayan)',
            ],
            [
                'category' => 'religion',
                'value' => 'United Church of Christ in the Philippines',
                'label' => 'United Church of Christ in the Philippines',
                'color' => '#84CC16',
                'sort_order' => 19,
                'is_active' => true,
                'description' => 'United Church of Christ in the Philippines',
            ],
            [
                'category' => 'religion',
                'value' => 'Church of Christ',
                'label' => 'Church of Christ',
                'color' => '#6366F1',
                'sort_order' => 20,
                'is_active' => true,
                'description' => 'Church of Christ',
            ],
            [
                'category' => 'religion',
                'value' => 'Other Christian',
                'label' => 'Other Christian',
                'color' => '#64748B',
                'sort_order' => 21,
                'is_active' => true,
                'description' => 'Other Christian denominations',
            ],
            [
                'category' => 'religion',
                'value' => 'No Religion',
                'label' => 'No Religion',
                'color' => '#6B7280',
                'sort_order' => 22,
                'is_active' => true,
                'description' => 'No religious affiliation',
            ],
            [
                'category' => 'religion',
                'value' => 'None',
                'label' => 'None',
                'color' => '#9CA3AF',
                'sort_order' => 23,
                'is_active' => true,
                'description' => 'None',
            ],
            [
                'category' => 'religion',
                'value' => 'Others',
                'label' => 'Others',
                'color' => '#64748B',
                'sort_order' => 24,
                'is_active' => true,
                'description' => 'Other religions not listed',
            ],
        ];

        foreach ($options as $option) {
            SystemOption::updateOrCreate(
                [
                    'category' => $option['category'],
                    'value' => $option['value'],
                ],
                $option
            );
        }

        $this->command->info('System options seeded successfully!');
    }
}
